name: plugin-updates push
on:
  release:
    types: [ published ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: build
        run: |
          set -x
          set -e
          BRANCH_NAME=`echo ${{github.event.ref}}`
          make zipball
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'dist.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
